// <auto-generated />
namespace Alpha.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inheritance_addons_and_accessories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inheritance_addons_and_accessories));
        
        string IMigrationMetadata.Id
        {
            get { return "201510291912326_inheritance_addons_and_accessories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
