// <auto-generated />
namespace Alpha.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Game_Details_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Game_Details_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201511031243494_Game_Details_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
